language: go


sudo: required

go:
  - 1.7
  - tip

service: 
  - mongodb

before_script:

  - 'echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty multiverse" | sudo tee /etc/apt/sources.list.d/multiverse.list'
  - sudo apt-get update
  - "sudo apt-get remove -y mongodb-org-server"
  - sudo apt-get install mongodb-org
  - sudo service mongod start
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - bash ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt

env:
  - DB_NAME=urlshortener
  - DB_HOST=localhost