language: go
sudo: false
go:
  - 1.7
  - tip

script:
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash ./coverage.sh
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt
notifications: