language: go
sudo: false
go:
  - 1.7
  - tip

service: 
  - mongodb

before_script:
  - sleep 15
  - sudo service mongod start
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script:
  - bash ./coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - rm coverage.txt

notifications: